[package]
name = "mathlib"
version = "0.2.0"
edition = "2024"

[dependencies]
libc = "0.2"

[build-dependencies]
pkg-config = "0.3"

[dev-dependencies]
criterion = "0.5"
num-bigint = "0.4"
num-traits = "0.2"
proptest = "1.4"

[features]
default = ["avx2", "gmp"]
gmp = []
avx2 = []

[[bench]]
name = "math_bench"
harness = false