[package]
name = "mathlib"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
criterion = "0.7.0"
rand = "0.8"

[[bench]]
name = "layout_benchmark"
harness = false

[[bench]]
name = "branch_benchmark"
harness = false

[[bench]]
name = "field_add_bench"
harness = false