[package]
name = "mathlib"
version = "0.2.0"
edition = "2024"

[dependencies]
libc = "0.2"
cfg-if = "1.0"
rand = "0.8"

[build-dependencies]
cc = "1.0"
pkg-config = "0.3"

[dev-dependencies]
criterion = "0.5"
num-bigint = "0.4"
num-traits = "0.2"
proptest = "1.4"

[features]
default = ["gmp"]
std = []
gmp = []
avx2 = []