[package]
name = "mathlib"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8"

[dev-dependencies]
criterion = "0.7.0"

[[bench]]
name = "layout_benchmark"
harness = false

[[bench]]
name = "branch_benchmark"
harness = false

[[bench]]
name = "xor_benchmark"
harness = false